export const FEATURE_KEYS = [
  "moneyPilot",
  "billNegotiator",
  "weekendPlanner",
  "mealPlanner",
  "shoppingLists",
  "chat",
  "receiptScanner",
  "priceAnalysis",
  "transactionMerge",
  "importCsv",
  "importAi",
  "importTelegram",
  "dashPrediction",
  "dashBudgets",
  "dashSavings",
  "dashDebts",
  "dashCategoryChart",
  "dashHeatmap",
  "dashCharts",
  "txAdd",
  "txEdit",
  "txDelete",
  "txSplit",
  "txItems",
  "txConfirm",
  "spendingWrapped",
  "moneyMap",
  "dashPriceWatch",
  "profileIncome",
  "profilePayments",
  "profileSubscriptions",
  "profileCashflow",
  "profileGoals",
  "profileHousehold",
  "profileTips",
  "profileChallenges",
  "profileTravel",
  "dashNetWorth",
  "dashMood",
  "txMood",
  "txMerchants",
] as const;

export type FeatureKey = (typeof FEATURE_KEYS)[number];

export type FeatureFlags = Record<FeatureKey, boolean>;

export const DEFAULT_FEATURE_FLAGS: FeatureFlags = {
  moneyPilot: true,
  billNegotiator: true,
  weekendPlanner: true,
  mealPlanner: true,
  shoppingLists: true,
  chat: true,
  receiptScanner: true,
  priceAnalysis: true,
  transactionMerge: true,
  importCsv: true,
  importAi: true,
  importTelegram: true,
  dashPrediction: true,
  dashBudgets: true,
  dashSavings: true,
  dashDebts: true,
  dashCategoryChart: true,
  dashHeatmap: true,
  dashCharts: true,
  txAdd: true,
  txEdit: true,
  txDelete: true,
  txSplit: true,
  txItems: true,
  txConfirm: true,
  spendingWrapped: true,
  moneyMap: true,
  dashPriceWatch: true,
  profileIncome: true,
  profilePayments: true,
  profileSubscriptions: true,
  profileCashflow: true,
  profileGoals: true,
  profileHousehold: true,
  profileTips: true,
  profileChallenges: true,
  profileTravel: true,
  dashNetWorth: true,
  dashMood: true,
  txMood: true,
  txMerchants: true,
};

export const FEATURE_LABELS: Record<FeatureKey, { label: string; description: string }> = {
  moneyPilot: { label: "Money Pilot", description: "AI-powered financial planning, scoring, and investment suggestions" },
  billNegotiator: { label: "Bill Negotiator", description: "AI bill negotiation suggestions" },
  weekendPlanner: { label: "Weekend Planner", description: "AI weekend activity planner" },
  mealPlanner: { label: "Meal Planner", description: "AI weekly meal planner" },
  shoppingLists: { label: "Shopping Lists", description: "Create and manage shopping lists" },
  chat: { label: "Money Chat", description: "AI chat assistant" },
  receiptScanner: { label: "Receipt Scanner", description: "AI receipt item extraction" },
  priceAnalysis: { label: "Price Analysis", description: "Item price tracking and comparison" },
  transactionMerge: { label: "Transaction Merge", description: "Merge duplicate transactions" },
  importCsv: { label: "Import CSV", description: "Import transactions from CSV files" },
  importAi: { label: "Import AI", description: "Import transactions using AI image analysis" },
  importTelegram: { label: "Import Telegram", description: "Import transactions from Telegram chat history" },
  dashPrediction: { label: "Expense Prediction", description: "AI expense prediction card on dashboard" },
  dashBudgets: { label: "Budget Progress", description: "Budget progress card on dashboard" },
  dashSavings: { label: "Savings Goals", description: "Savings goals card on dashboard" },
  dashDebts: { label: "Debts", description: "Debts card on dashboard" },
  dashCategoryChart: { label: "Category Chart", description: "Monthly category breakdown chart on dashboard" },
  dashHeatmap: { label: "Spending Heatmap", description: "Daily spending heatmap on dashboard" },
  dashCharts: { label: "Charts", description: "Monthly bar, donut, merchants, and trend charts on dashboard" },
  txAdd: { label: "Add Transaction", description: "Add new transactions" },
  txEdit: { label: "Edit Transaction", description: "Edit existing transactions" },
  txDelete: { label: "Delete Transaction", description: "Delete transactions" },
  txSplit: { label: "Split Transaction", description: "Split transactions between people/categories" },
  txItems: { label: "Line Items", description: "View and manage transaction line items" },
  txConfirm: { label: "Confirm Transaction", description: "Confirm unconfirmed transactions" },
  spendingWrapped: { label: "Spending Wrapped", description: "Monthly/yearly spending summary with slides" },
  moneyMap: { label: "Money Map", description: "Location-based spending visualization" },
  dashPriceWatch: { label: "Price Watch", description: "Price alerts card on dashboard" },
  profileIncome: { label: "Income & Saving", description: "Income and savings tab in profile" },
  profilePayments: { label: "Payments", description: "Bills and payments tab in profile" },
  profileSubscriptions: { label: "Subscriptions", description: "Subscriptions tab in profile" },
  profileCashflow: { label: "Cashflow", description: "Cashflow calendar tab in profile" },
  profileGoals: { label: "Goals", description: "Savings goals tab in profile" },
  profileHousehold: { label: "Household", description: "Household management tab in profile" },
  profileTips: { label: "Financial Tips", description: "Financial tips on profile overview" },
  profileChallenges: { label: "Challenges", description: "Savings challenges and badges" },
  profileTravel: { label: "Travel", description: "Travel tracking and trip management" },
  dashNetWorth: { label: "Net Worth", description: "Net worth card on dashboard" },
  dashMood: { label: "Money Mood", description: "Money mood stats card on dashboard" },
  txMood: { label: "Transaction Mood", description: "Mood picker column in transactions list" },
  txMerchants: { label: "Merchants", description: "Merchants management tab" },
};

export function parseFeatureFlags(raw: unknown): FeatureFlags {
  const flags = { ...DEFAULT_FEATURE_FLAGS };
  if (raw && typeof raw === "object" && !Array.isArray(raw)) {
    for (const key of FEATURE_KEYS) {
      if (key in (raw as Record<string, unknown>) && typeof (raw as Record<string, boolean>)[key] === "boolean") {
        flags[key] = (raw as Record<string, boolean>)[key];
      }
    }
  }
  return flags;
}
